import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { BookProvider } from "@/context/BookContext";
import { BooksStorageProvider } from "@/context/BooksStorageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BookProvider>
        <BooksStorageProvider>
          <body className={`${inter.className} antialiased`}>{children}</body>
        </BooksStorageProvider>
      </BookProvider>
    </html>
  );
}
